services:

  deno_service:
    build:
      context: .
      dockerfile: ./infra/deno_service/Dockerfile
    ports:
      - ${HTTP_PORT:-80}:80
    restart: always
    depends_on:
      - php_fpm_service

  php_fpm_service:
    build:
      context: .
      dockerfile: ./infra/php_fpm_service/Dockerfile
    restart: always
